CREATE TABLE IF NOT EXISTS "power_consumption_nsm"(
  "UNIQUE_CODE" TEXT,
  "ACCOUNT_NO" TEXT,
  "METER_TYPE" TEXT,
  "BRANCH" TEXT,
  "CSC" TEXT,
  "TARIFF" TEXT,
  "YEAR" TEXT,
  "MONTH" TEXT,
  "CONSUMPTION" NUMERIC
);
