CREATE TABLE IF NOT EXISTS "power_consumption_sm"(
  "SERIAL" TEXT,
  "CUSTOMER_REF" TEXT,
  "TIMESTAMP" TEXT,
  "OBIS" TEXT,
  "DATE" TEXT,
  "TIME" TEXT,
  "IMPORT_KWH (kWh)" TEXT,
  "EXPORT_KWH (kWh)" TEXT,
  "IMPORT_KVARH (kvarh)" TEXT,
  "EXPORT_KVARH (kvarh)" TEXT,
  "PHASE_A_INST._CURRENT (A)" TEXT,
  "PHASE_B_INST._CURRENT (A)" TEXT,
  "PHASE_C_INST._CURRENT (A)" TEXT,
  "PHASE_A_INST._VOLTAGE (V)" TEXT,
  "PHASE_B_INST._VOLTAGE (V)" TEXT,
  "PHASE_C_INST._VOLTAGE (V)" TEXT,
  "POWER_FACTOR" TEXT,
  "AVG._IMPORT_KW (kW)" TEXT,
  "AVG._EXPORT_KW (kW)" TEXT,
  "AVG._IMPORT_KVA (kVA)" TEXT,
  "AVG._EXPORT_KVA (kVA)" TEXT,
  "AVG._CURRENT (V)" TEXT,
  "AVG._VOLTAGE (V)" TEXT
);


